/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GamesIndexRouteImport } from './routes/games/index'
import { Route as GamesGameSlugRouteImport } from './routes/games/$gameSlug'
import { Route as AuthenticatedSignOutRouteImport } from './routes/_authenticated/sign-out'
import { Route as AuthenticatedPrivateTestRouteImport } from './routes/_authenticated/private-test'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIndexRoute = GamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesGameSlugRoute = GamesGameSlugRouteImport.update({
  id: '/games/$gameSlug',
  path: '/games/$gameSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSignOutRoute = AuthenticatedSignOutRouteImport.update({
  id: '/sign-out',
  path: '/sign-out',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPrivateTestRoute =
  AuthenticatedPrivateTestRouteImport.update({
    id: '/private-test',
    path: '/private-test',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/journal': typeof JournalRoute
  '/login': typeof LoginRoute
  '/sign-up': typeof SignUpRoute
  '/private-test': typeof AuthenticatedPrivateTestRoute
  '/sign-out': typeof AuthenticatedSignOutRoute
  '/games/$gameSlug': typeof GamesGameSlugRoute
  '/games': typeof GamesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/journal': typeof JournalRoute
  '/login': typeof LoginRoute
  '/sign-up': typeof SignUpRoute
  '/private-test': typeof AuthenticatedPrivateTestRoute
  '/sign-out': typeof AuthenticatedSignOutRoute
  '/games/$gameSlug': typeof GamesGameSlugRoute
  '/games': typeof GamesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/journal': typeof JournalRoute
  '/login': typeof LoginRoute
  '/sign-up': typeof SignUpRoute
  '/_authenticated/private-test': typeof AuthenticatedPrivateTestRoute
  '/_authenticated/sign-out': typeof AuthenticatedSignOutRoute
  '/games/$gameSlug': typeof GamesGameSlugRoute
  '/games/': typeof GamesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/journal'
    | '/login'
    | '/sign-up'
    | '/private-test'
    | '/sign-out'
    | '/games/$gameSlug'
    | '/games'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/journal'
    | '/login'
    | '/sign-up'
    | '/private-test'
    | '/sign-out'
    | '/games/$gameSlug'
    | '/games'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/journal'
    | '/login'
    | '/sign-up'
    | '/_authenticated/private-test'
    | '/_authenticated/sign-out'
    | '/games/$gameSlug'
    | '/games/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  JournalRoute: typeof JournalRoute
  LoginRoute: typeof LoginRoute
  SignUpRoute: typeof SignUpRoute
  GamesGameSlugRoute: typeof GamesGameSlugRoute
  GamesIndexRoute: typeof GamesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/': {
      id: '/games/'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$gameSlug': {
      id: '/games/$gameSlug'
      path: '/games/$gameSlug'
      fullPath: '/games/$gameSlug'
      preLoaderRoute: typeof GamesGameSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sign-out': {
      id: '/_authenticated/sign-out'
      path: '/sign-out'
      fullPath: '/sign-out'
      preLoaderRoute: typeof AuthenticatedSignOutRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/private-test': {
      id: '/_authenticated/private-test'
      path: '/private-test'
      fullPath: '/private-test'
      preLoaderRoute: typeof AuthenticatedPrivateTestRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedPrivateTestRoute: typeof AuthenticatedPrivateTestRoute
  AuthenticatedSignOutRoute: typeof AuthenticatedSignOutRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedPrivateTestRoute: AuthenticatedPrivateTestRoute,
  AuthenticatedSignOutRoute: AuthenticatedSignOutRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  JournalRoute: JournalRoute,
  LoginRoute: LoginRoute,
  SignUpRoute: SignUpRoute,
  GamesGameSlugRoute: GamesGameSlugRoute,
  GamesIndexRoute: GamesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
